// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type CurrentEpochReq struct {
	Symbol string `json:"symbol,optional,example=cuniBTC"` //symbol of the strategy, empty indicate all
}

type CurrentEpochResp struct {
	Epoch                 uint64 `json:"epoch,example=10"`                         //epoch number
	OperateStartTimestamp uint64 `json:"operateStartTimestamp,example=1777349793"` // operate startTime
	OperatePeriod         uint64 `json:"operatePeriod,example=86400"`              // operate period in second
	LockupStartTimestamp  uint64 `json:"lockupStartTimestamp,example=1777649793"`  //lockup startTime
	LockupPeriod          uint64 `json:"lockupPeriod,example=86400"`               //lockup period in second
	Symbol                string `json:"symbol,example=cuniBTC"`                   //symbol of the stratedy
}

type ListReq struct {
	Limit  int `json:"limit,example=10,default=10,range=[1:50]"` //Number of items per page
	Offset int `json:"offset,example=0,default=0"`               //Data offset
}

type PageData struct {
	Total  int64 `json:"total,example=1234"`         //Total data count
	Limit  int   `json:"limit,example=10"`           //Number of items per page, consistent with the request
	Offset int   `json:"offset,example=0,default=0"` //Data offset, consistent with the request
}

type PositionOverviewReq struct {
	Symbol  string `json:"symbol,optional,example=cuniBTC"` //symbol of the strategy, empty indicate all
	Address string `json:"address,example=0x8cb37518330014E027396E3ED59A231FBe3B011A"`
}

type PositionOverviewResp struct {
	Symbol      string `json:"symbol,example=cuniBTC"`       //symbol of the stratedy
	Amount      string `json:"amount,example=0.023"`         //amount of this symbol
	Earning     string `json:"earning,example=0.023243"`     //amount earning human readable
	Queued      string `json:"queued,example=0.023243"`      //amount queued human readable
	Withdrawing string `json:"withdrawing,example=0.023243"` //amount withdrawing human readable
	Rewards     string `json:"rewards,example=0.023243"`     //amount withdrawing human readable
}

type TotalEarnedReq struct {
	Symbol  string `json:"symbol,optional,example=cuniBTC"` //symbol of the strategy, empty indicate all
	Address string `json:"address,example=0x8cb37518330014E027396E3ED59A231FBe3B011A"`
}

type TotalEarnedResp struct {
	Symbol      string `json:"symbol,example=cuniBTC"`       //symbol of the stratedy
	TotalEarned string `json:"totalEarned,example=0.023243"` //amount earned human readable
}
