// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	"cuniBTCReward/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/currentEpoch",
				Handler: CurrentEpochHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/positionOverview",
				Handler: PositionOverviewHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/totalEarned",
				Handler: TotalEarnedHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/uniBTCPrice",
				Handler: UniBTCPriceHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/ping",
				Handler: pingHandler(serverCtx),
			},
		},
	)
}
